name: linkelio_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  tekartik_app_cv_firestore:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_firestore
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_http
  tekartik_mustache:
    git:
      url: https://github.com/tekartik/mustache.dart
      path: mustache
  tkcms_common:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      path: packages/tkcms_common
  # path: ^1.8.0

dev_dependencies:
  lints: ">=5.0.0"
  test: '>=1.24.0'
